//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Data.Objects;
using System.Data.Objects.DataClasses;
using System.Data.EntityClient;
using System.ComponentModel;
using System.Xml.Serialization;
using System.Runtime.Serialization;

[assembly: EdmSchemaAttribute()]

namespace CbaGob.Alumnos.Repositorio.Models
{
    #region Contexts
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    public partial class ComunicacionesDB : ObjectContext
    {
        #region Constructors
    
        /// <summary>
        /// Initializes a new ComunicacionesDB object using the connection string found in the 'ComunicacionesDB' section of the application configuration file.
        /// </summary>
        public ComunicacionesDB() : base("name=ComunicacionesDB", "ComunicacionesDB")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        /// <summary>
        /// Initialize a new ComunicacionesDB object.
        /// </summary>
        public ComunicacionesDB(string connectionString) : base(connectionString, "ComunicacionesDB")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        /// <summary>
        /// Initialize a new ComunicacionesDB object.
        /// </summary>
        public ComunicacionesDB(EntityConnection connection) : base(connection, "ComunicacionesDB")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        #endregion
    
        #region Partial Methods
    
        partial void OnContextCreated();
    
        #endregion
    
    }
    

    #endregion
    
    
}
